# Form implementation generated from reading ui file 'C:\Users\Maks\Desktop\Congrats.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from des import Ui_MainWindow


class Ui_Congrats(object):
    def setupUi(self, Congrats):
        Congrats.setObjectName("Congrats")
        Congrats.resize(303, 177)
        self.label = QtWidgets.QLabel(parent=Congrats)
        self.label.setGeometry(QtCore.QRect(60, 40, 201, 91))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Congrats)
        QtCore.QMetaObject.connectSlotsByName(Congrats)

    def retranslateUi(self, Congrats):
        _translate = QtCore.QCoreApplication.translate
        Congrats.setWindowTitle(_translate("Congrats", "Congrats!!!"))
        self.label.setText(_translate("Congrats", "Congrats!!!"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Congrats = QtWidgets.QWidget()
    ui = Ui_Congrats()
    ui.setupUi(Congrats)
    Congrats.show()
    sys.exit(app.exec())
